version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - dev-network

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka:/bitnami/kafka
    networks:
      - dev-network
    depends_on:
      - zookeeper

  kadeck:
    image: 'xeotek/kadeck:5.3.0'
    ports:
      - '8000:80'
    environment:
      - xeotek_kadeck_free="eryxlee@163.com"
      - xeotek_kadeck_port=80
    volumes:
      - ./kafka/kadeck:/root/.kadeck/ 
    networks:
      - dev-network
    depends_on:
      - zookeeper
      - kafka

networks:
  dev-network:
